### ISSUE TITLE
Policy labels showing resource types are not correct

### ISSUE THREAD

**Issue by kravciak** [rancher/kubewarden-ui#257]
### Current Behavior

List of policies from artifacthub shows label showing policy resource type (`Pod`, `Service`, `Custom`, `Multiple`, `Ingress`, `Global`).

Those labels are incorrect, for example `User Group PSP` or `Pod Privileged Policy` label is `Pod`, but rules target multiple resources.

![Screenshot from 2023-02-22 10-31-38](https://user-images.githubusercontent.com/538604/220580957-cf85e4f0-77bf-4cfe-a45b-baf46096b47f.png)

### Expected Behavior

Correct resource type or no label

**Comment by jordojordo** [comment]
@kravciak The resources are contained in the policy's [artifacthub pkg metadata](https://github.com/kubewarden/pod-privileged-policy/blob/7dcf90e3c69926f0989f3d05803c5980dde43bd3/artifacthub-pkg.yml#L27), looks like this was missed when the rules were updated.

**Comment by viccuad** [comment]
This will get fixed once the [artifacthub automation is released](https://github.com/kubewarden/kubewarden-controller/issues/389), and the policies have been re-released.

**Comment by jordojordo** [comment]
These policies are still missing the resources from the metadata:
- [allowed-proc-mount-types-psp](https://github.com/kubewarden/allowed-proc-mount-types-psp-policy/blob/fea90343a122b1249a1e7bf0d9c1e40183c1b20a/artifacthub-pkg.yml#L58)
- [pod-privileged-policy](https://github.com/kubewarden/pod-privileged-policy/blob/590070c7ac4890416d82f00afd8f5b9b067b7c24/artifacthub-pkg.yml#L41)
- [user-group-psp](https://github.com/kubewarden/user-group-psp-policy/blob/0faaf3e97d6b60ea3454c30efc87b55ec0a45d22/artifacthub-pkg.yml#L216)

These will need to be updated with a new version released for each.

**Comment by jordojordo** [comment]
This has been fixed in #734
