### ISSUE TITLE
Admission policy creation screen needs improvement

### ISSUE THREAD

**Issue by kwwii** [rancher/kubewarden-ui#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The icons included in the cards do not fit properly. The colors used should add meaning based on the type of policy (pod, ingress global, etc.).

### Environment

```markdown
- OS:
- Architecture:
```

### Anything else?

<img width="1436" alt="grafik" src="https://user-images.githubusercontent.com/617368/164262679-70e386ce-54ba-425e-9537-796e794e219d.png">

**Comment by jordojordo** [comment]
> The colors used should add meaning based on the type of policy (pod, ingress global, etc.).
@kwwii Is this referring to the colors of the icons or the badges?

**Comment by kwwii** [comment]
https://xd.adobe.com/view/86578da5-2dd3-435d-8e83-bf2f4dec827c-d304/

**Comment by kwwii** [comment]
The first thing to take care of is the size of the icons themselves within the circles. The icon should fit within the circle with a bit of padding, not be cut off on the edges by the circle.

**Comment by jordojordo** [comment]
Should we remove the icons entirely? If we go with the "Simple Cards with Tags" approach from [here](https://xd.adobe.com/view/86578da5-2dd3-435d-8e83-bf2f4dec827c-d304/) we would have no use for the icons.
