### ISSUE TITLE
Update documentation to support air-gap installation

### ISSUE THREAD

**Issue by jordojordo** [rancher/kubewarden-ui#426]
The documentation as well as the Readme should be updated to explain the air-gap installation flow.

- [x] #430
- [ ] Update the documentation on `docs.kubewarden.io`

**Comment by flavio** [comment]
We should update [our documentation](https://docs.kubewarden.io/operator-manual/airgap/install) to ensure the UI plugin operator container image to the list of images that have to be mirrored.
