### ISSUE TITLE
Update the policy-reporter installation steps

### ISSUE THREAD

**Issue by jordojordo** [rancher/kubewarden-ui#473]
With the `kubewarden-controller` version `1.7.0-rc3`, the helm chart including the policy-reporter will be automatically installed. This will remove the necessary user interaction to install the policy-reporter chart manually, so the installation wizard should be modified to fit this behavior.

**Comment by viccuad** [comment]
Just for clarity, one needs to install the `kubewarden-controller` chart with `.Values.auditScanner.policyReporter` set to `true`, as it is `false` by default. I don't know if the UI sets that value to `true` on its own (I would expect yes).

**Comment by jordojordo** [comment]
It doesn't seem to set it to true by default, would it be possible to add this to one of the UI questions? I think this setting would be easily missed.

**Comment by viccuad** [comment]
Good point, I agree it should be added to the UI questions. We can either take care of the questions completely in UI, or use questions.yml of the kubewarden-controller chart.

For questions.yml, we would need to set `.Values.auditScanner.policyReporter`, and possibly, expose or create questions for the policy-reporter subchart values, see: https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-controller/chart-values.yaml#L118-L130. I suppose those values may grow in the future.
It would also be super nice to have a tab for Policy Reporter in the UI of questions, just like we do for other things.
