### ISSUE TITLE
Check for cert-manager CRDs instead of Service during installation

### ISSUE THREAD

**Issue by jordojordo** [rancher/kubewarden-ui#488]
During the installation of the kubewarden-controller there is a step for installing `cert-manager`, in order for this step to advance it is [checking for the existence](https://github.com/rancher/kubewarden-ui/blob/c2bad0212556431848678079aebf29c412580a60/pkg/kubewarden/components/Dashboard/InstallView.vue#L113-L115) of a Service with the label: `app: cert-manager`. This should be changed to instead check for the existence of the cert-manager CRDs rather than a Service and label since users could have installed cert-manager previously with their own specifications.

**Comment by flavio** [comment]
I think we can close this issue, since we are going to entirely remove the cert-manager dependency (see https://github.com/rancher/kubewarden-ui/issues/489)
