### ISSUE TITLE
Metrics: Collapsed grafana panels show `Loading...` state

### ISSUE THREAD

**Issue by kravciak** [rancher/kubewarden-ui#534]
When I collapse Grafana panels I get `Loading...` state until I change page.
This does not happen if I open Grafana in it's own tab.

[Screencast from 2023-10-30 15-20-45.webm](https://github.com/rancher/kubewarden-ui/assets/538604/89067a3e-6411-43ed-9e3d-8de7d0a7a4a0)

**Comment by jordojordo** [comment]
This appears to be an issue with the [GrafanaDashboard component](https://github.com/rancher/dashboard/blob/master/shell/components/GrafanaDashboard.vue) coming from the `@rancher/shell` package. I'll have to do some testing to narrow this one down and possibly transfer the issue.

**Comment by aalves08** [comment]
I cannot fix this at this point @kravciak ... I agree with @jordojordo assessment, but the main problem now is that we still aren't able to release a new shell version at this point in time, so no point in trying to fix/debug it at this point
