### ISSUE TITLE
Policy Reporter Link goes to "local" Cluster even though we selected a downstream cluster

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/kubewarden-ui#545]
We can only see policy reporter in local cluster - never in downstream cluster when using the rancher UI extension integration of policy reporter.

rke-test is the downstream cluster:
(URL: https://rancher.suse/dashboard/c/c-m-x8d85l5v/kubewarden/policy-reporter)
![grafik](https://github.com/rancher/kubewarden-ui/assets/13362573/2b6f8868-0cac-4275-ac7d-92ae86e4414e)

local is the rancher cluster:
(URL: https://rancher.suse/dashboard/c/local/kubewarden/policy-reporter)
![grafik](https://github.com/rancher/kubewarden-ui/assets/13362573/0e692430-760d-4fad-a78b-99ff90819e86)

Steps to reproduce:

Deploy kubewarden in Rancher local cluster and in downstream cluster.
Then access the Policy Reporter in local cluster and compare this with accessing the Policy Reporter in downstream cluster
-> both are exactly the same so we can alway "only" see the local clusters policy report.

Issue: we see policy reporter results of rancher local cluster

Expectation: we can see the policy server results of the downstream cluster when we select them.

**Comment by Martin-Weiss** [comment]
On the CLI we can see different report results:

local cluster:
![grafik](https://github.com/rancher/kubewarden-ui/assets/13362573/332dbafe-c492-40a9-93bc-5be1ae0faac6)

downstream cluster:
![grafik](https://github.com/rancher/kubewarden-ui/assets/13362573/61e6e54a-187a-4dcf-834b-c53820bd8c10)

**Comment by Martin-Weiss** [comment]
FYI - this link works to access the downstream: https://rancher.suse/k8s/clusters/c-m-x8d85l5v/api/v1/namespaces/kubewarden/services/http:kubewarden-controller-ui:8080/proxy/#/

**Comment by jordojordo** [comment]
This has been fixed with #522 - the proxy URL was not prepending the cluster id and thus pointing to the Local cluster by default.

With `1.3.0-rc2`, you can see the correct link when hovering over the "Policy Reporter UI" link at the top right, also note I do not have the Reporter installed on my local cluster:
![pr](https://github.com/rancher/kubewarden-ui/assets/40806497/2552eda4-37bd-4cfc-bcf9-32dc0b8a1cd4)
