### ISSUE TITLE
UI shows pre-release -rc policies

### ISSUE THREAD

**Issue by kravciak** [rancher/kubewarden-ui#590]
Today we released Container resources policy [Release v0.1.0-rc1](https://github.com/kubewarden/container-resources-policy/releases/tag/v0.1.0-rc1)

### Current state
Policy is visible in the UI in version `container-resources:v0.1.0-rc1`

### Expected state
`-rc` policy is not visible in the UI until stable version (or visibility can be based `Include Prerelease Versions` setting).

**Comment by jordojordo** [comment]
I can add the same computation to determine a pre-release version as we are doing for the controller chart upgrade button. When I do this I'm able to filter out the Container Resources policy correctly, but it is also filtering out the Deprecated API Versions policy. How should I determine if [these versions](https://github.com/kubewarden/deprecated-api-versions-policy/releases) are pre-release? For instance, the version `v0.1.12-k8sv1.29.0` computed by the [node-semver package function `prerelease`](https://github.com/npm/node-semver?tab=readme-ov-file#functions) will return an array of `[ "k8sv1", 29, 0 ]` - should this be considered an rc?

There is a `prerelease` property on the [ArtifactHub package schema](https://artifacthub.io/docs/api/#/Packages/getKubewardenPoliciesDetails) that could be determined for this purpose, but that is not set on any policy at the moment.

![package-schema](https://github.com/rancher/kubewarden-ui/assets/40806497/d07fdc6a-aeb7-475d-9fbb-dbe867d332ff)

**Comment by kravciak** [comment]
@flavio what do you think?
