### ISSUE TITLE
request filter `filter: labelSelector=app.kubernetes.io/managed-by=kubewarden` not working in shell `0.5.3`

### ISSUE THREAD

**Issue by aalves08** [rancher/kubewarden-ui#645]
While doing a developer load of Kubewarden for the Policy Reports with `filter: labelSelector=app.kubernetes.io/managed-by=kubewarden`, it's not working against Rancher `2.8.2` or shell `0.5.3`.

Once we've figured where exactly the problem lies, we need to bring back the selector `selector: 'app.kubernetes.io/managed-by=kubewarden'` to the `fetchPolicyReports` function in `modules/policyReporter.ts`

also, the dispatch in `fetchPolicyReports` should be `cluster/findMatching` and not `cluster/findAll`

```
return await store.dispatch('cluster/findMatching', {
    type:     WG_POLICY_K8S.POLICY_REPORT.TYPE,
    selector: 'app.kubernetes.io/managed-by=kubewarden'
  }, { root: true });
```

Maybe we can get this back when releasing Rancher Dashboard `2.9.0`

**Comment by aalves08** [comment]
FYI @jordojordo

**Comment by jordojordo** [comment]
This issue is no longer occurring as we have changed how we are filtering the policy reports that have been fetched.
