### ISSUE TITLE
Bug: Grafana dropdown is not correctly selected on embedded grafana pane

### ISSUE THREAD

**Issue by viccuad** [rancher/kubewarden-ui#649]
### Problem

Some time ago we added a dropdown to the Grafana dashboard to show results per policy, see [here](https://github.com/rancher/kubewarden-ui/pull/284).

Currently, when opening the metrics tab of a policy, where the Grafana dashboard pane is embedded, it seems that the dropdown has not been correctly selected.

See, showing `clusterwide-drop-capabilities` results instead of `no-host-namespace-sharing`: 

![313247680-fdc304c4-b51b-426f-b6e8-c62524f697ee](https://github.com/rancher/kubewarden-ui/assets/2196685/1c1c3ea4-6dee-4756-9cfd-850db58064d5)

In contrast with the Grafana dashboard with the correct dropdown policy name selected:

![image (1)](https://github.com/rancher/kubewarden-ui/assets/2196685/954b4af8-7fbc-4761-b6a1-d8b1217fb1b5)

**Comment by flavio** [comment]
CC @aalves08
