### ISSUE TITLE
Projects/Namespaces show only last policyreport

### ISSUE THREAD

**Issue by kravciak** [rancher/kubewarden-ui#656]
We have 3 policyreports in default namespace
```bash
~ k get policyreports.wgpolicyk8s.io -n default
NAME                                   PASS   FAIL   WARN   ERROR   SKIP   AGE
88f7c0a2-418e-42f5-a099-277fe97d3fe0   0      1      0      0       0      41m
fb6c082b-1469-44ab-a492-0e200dbe959c   3      4      0      0       0      41m
2a6602c4-e86e-438b-b68b-dbe6c00dc2b0   3      4      0      0       0      41m
```

UI shows numbers only from last report, order changes randomly.

![Screenshot from 2024-03-19 16-37-08](https://github.com/rancher/kubewarden-ui/assets/538604/32e7f9b4-e851-467b-9e94-494187c98dce)

We discussed with @viccuad about 2 options:
 - as immediate fix we could show compliance report for default namespace itself
 - show aggregate numbers from all the resources in that namespace, which might be costly for big namespaces

**Comment by viccuad** [comment]
I favour "show compliance report for default namespace itself", which is also simple to implement: obtain uid of namespace (or clusterwide resource) under eval, query for clusterpolicyreport with metadata.name == uid of the resource under eval.
