### ISSUE TITLE
[Bug] Update chart install routes

### ISSUE THREAD

**Issue by jordojordo** [rancher/kubewarden-ui#792]
When running the extension in Rancher v2.9-head (`v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head`), the route for chart installations is broken. A workaround would be to use the `/chart` route instead of `/install` when redirecting the user to install a chart.

**Comment by richard-cox** [comment]
https://github.com/rancher/dashboard/issues/11126 will now be addressed in 2.9.0, once completed this issue can be closed
