### ISSUE TITLE
Can't edit recommended policy settings after page reload

### ISSUE THREAD

**Issue by kravciak** [rancher/kubewarden-ui#806]
[Screencast from 2024-07-19 22-31-47.webm](https://github.com/user-attachments/assets/51f80d6d-3b1b-4169-9dfe-31229d08f8a1)

rancher 2.9.0-alpha7
kubewarden: built from main

**Comment by jordojordo** [comment]
This is related to #792 which has been fixed in the latest `rancher/dashboard` builds. Rancher version `v2.9.0-alpha7` does not have this fix.
