### ISSUE TITLE
Remove cert-manager requirement step for Kubewarden version `1.17`

### ISSUE THREAD

**Issue by jordojordo** [rancher/kubewarden-ui#839]
With the advent of Kubewarden version `1.17`, the requirement to have cert-manager will no longer be necessary. During the installation wizard within the UI we should then remove the cert-manager installation step.

**Comment by viccuad** [comment]
Note though that open-telemetry does depend on cert-manager (I don't remember if the UI already checks for it).

**Comment by jordojordo** [comment]
The UI does not check for cert-manager within the tracing or metrics checklist, that will have to be an added step.

**Comment by flavio** [comment]
@jvanz is going to do a quick investigation to assess whether cert-manager is required by tracing and metrics. If that's the case, we should keep the UI that deals with the installation of cert-menager around, maybe move it as part of the flow that leads to the installation of metrics and telemetry.

**Comment by jvanz** [comment]
Yes, OpenTelemetry requires certificate configuration to allow its webhooks work properly. 

> The easiest and default method is to install the [cert-manager](https://cert-manager.io/docs/) and set admissionWebhooks.certManager.create to true. In this way, cert-manager will generate a self-signed certificate. See [cert-manager installation](https://cert-manager.io/docs/installation/kubernetes/) for more details.

Therefore, if we want to follow the default configuration of OpenTelemetry, which uses cert-manager, we need to check if cert-manager is installed. I guess the best is to check when telemetry is enabled.

**Comment by flavio** [comment]
Don't forget there's also Jaeger, I suspect this one requires cert-manager too

**Comment by jvanz** [comment]
> Don't forget there's also Jaeger, I suspect this one requires cert-manager too

Yeap. https://github.com/jaegertracing/jaeger-operator/blob/main/COMPATIBILITY.md
